apiVersion: apps/v1
kind: Deployment 
metadata:
  name: socialapp-deployment
  labels:
    app: yashapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yashapp 
  template:
    metadata:
      labels:
        app: yashapp
    spec:
      containers:
      - name: yashapp
        image: yash059/socialtestapp123
        ports:
        - containerPort: 8080
