FROM openjdk:11
MAINTAINER Yash Yadav<yash.mlvt@gmail.com>
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/social-app-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} social-app-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/social-app-0.0.1-SNAPSHOT.jar"]
